# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 97f65a86d04c00f22a5e3294114d2a0a380bd9ce2c7599dde615d7fcd19d69bd949c21260d6627b36516cc710e0d53259783c6e7a71847eb3cd121429516e5ee

test:
  secret_key_base: 46d6193f2c7d69fbb15a7ee2b46e1a62f1367140fa703cd312432c06e6c0cb1319212e5f7415339c191d6549962f8bfce3be1fe27da09ea57385f72b64717e7e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
